In [27]:
import numpy as np
from solvematrix import *
for i in range(0, 5):
    m1 = 0.0
    m2 = 0.0
    m3 = 0.0

    if i == 0:
        m1 = 2.0
        m2 = 5.0
        m3 = 1.0
    elif i == 1:
        m1 = 2.0
        m2 = 2.0
        m3 = 2.0
    elif i == 2:
        m1 = 4.0
        m2 = 4.0
        m3 = 4.0
    elif i == 3:
        m1 = 0.0
        m2 = 5.0
        m3 = 1.0
    elif i == 4:
        m1 = 2.0
        m2 = 5.0
        m3 = 0.0

    M = np.zeros([4, 4], float)
    M[0,:] = [-m1, 0.0, 0.0, 1.0]
    M[1,:] = [0.0, -m2, 0.0, 1.0]
    M[2,:] = [0.0, 0.0, m3, 2.0]
    M[3,:] = [2.0, -1.0, -1.0, 0.0]
    b = np.array([0.0, 0.0, m3*9.8, 0.0])
    print("{}".format(solvematrix(M,b)))

## output formatted as following: [a1, a2, a3, T]

[1.75 0.7  2.8  3.5 ]
[3.26666667 3.26666667 3.26666667 6.53333333]
[ 3.26666667  3.26666667  3.26666667 13.06666667]
[4.9 0.  9.8 0. ]
[0. 0. 0. 0.]
